#!/bin/bash

xset -dpms
xset s off
xset s noblank

sleep 10

if [ -z "$SCREEN_ROTATION" ]
then
  echo "SCREEN_ROTATION not set"
else
  xrandr -o $SCREEN_ROTATION

  SEARCH="Touch"
  if [ "$SEARCH" = "" ]; then 
      exit 1
  fi
  echo $SEARCH
  ids=$(xinput --list | awk -v search="$SEARCH" \
      '$0 ~ search {match($0, /id=[0-9]+/);\
                    if (RSTART) \
                      print substr($0, RSTART+3, RLENGTH-3)\
                  }'\
      )

  echo $ids
  echo $SCREEN_ROTATION

  echo TEST-EDDIT---
  echo `xinput list`
  echo TEST-EDDIT---

  echo "Active Touch IDs:"  
  echo $ids
  cnt=0
  for i in $ids
  do
    if (( $cnt<2 )) 
    then
      cnt=$((cnt+1))
      if [ "$SCREEN_ROTATION" == "left" ]
      then                                                                 
        xinput set-prop $i "Coordinate Transformation Matrix" 0 -1 1 1 0 0 0 0 1
        echo $i
      elif [ "$SCREEN_ROTATION" == "right" ]
      then                                                                
        xinput set-prop $i "Coordinate Transformation Matrix" 0 1 0 -1 0 1 0 0 1
        echo $i
      elif [ "$SCREEN_ROTATION" == "inverted" ]                           
      then                                                                 
        xinput set-prop $i "Coordinate Transformation Matrix" -1 0 1 0 -1 1 0 0 1
        echo $i
      elif [ "$SCREEN_ROTATION" == "normal" ]
      then                                                                 
        xinput set-prop $i "Coordinate Transformation Matrix" 0 0 0 0 0 0 0 0 0
        echo $i
      fi
    fi
  done
fi

if [ -z "$SCREEN_XINIT" ]
then
  echo "SCREEN_XINIT not set"
else
  eval "$SCREEN_XINIT"
fi

# This path looks wrong so checking if file exists before attempting to run it
[ -f ../displaycheck.js ] && node ../displaycheck.js &

i3 &

cd /app
rm -rf /home/xorg/.config/Electron
mkdir -p /home/xorg/.config
mkdir -p /home/xorg/browsercache/Electron
ln -s /home/xorg/browsercache/Electron /home/xorg/.config/Electron
chown -R xorg /home/xorg
exec sudo -H -u xorg --preserve-env=activeUrl bash -c 'yarn prod'
# exec yarn prod

